ARG BASE_IMAGE=vllm/vllm-openai

FROM $BASE_IMAGE

# Metadata
LABEL io.k8s.display-name="GuideLLM" \
      org.opencontainers.image.description="GuideLLM Performance Benchmarking Container" \
      org.opencontainers.image.source="https://github.com/vllm-project/guidellm" \
      org.opencontainers.image.documentation="https://blog.vllm.ai/guidellm/stable" \
      org.opencontainers.image.license="Apache-2.0"

# release: take the last version and add a post if build iteration
# candidate: increment to next minor, add 'rc' with build iteration
# nightly: increment to next minor, add 'a' with build iteration
# alpha: increment to next minor, add 'a' with build iteration
# dev: increment to next minor, add 'dev' with build iteration
ARG GUIDELLM_BUILD_TYPE=dev

# Extra dependencies to install
# all: install all extras
# recommended: install recommended extras
# container: All extras except vllm
ARG GUIDELLM_BUILD_EXTRAS=container

# Switch to root for installing packages
USER root

RUN apt-get update || true \
    && apt-get install -y --no-install-recommends gnupg ca-certificates \
    && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 871920D1991BC93C \
    && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BA6932366A755776 \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y git \
    && rm -rf /var/lib/apt/lists/*

# Set correct build type for versioning
# Configure uv for building guidellm
ENV GUIDELLM_BUILD_TYPE=$GUIDELLM_BUILD_TYPE \
    VIRTUAL_ENV=/opt/app-root \
    UV_PROJECT="/src" \
    UV_LINK_MODE="copy" \
    UV_NO_DEV="1" \
    UV_NO_EDITABLE="1" \
    UV_FROZEN="1" \
    UV_CACHE_DIR="/tmp/uv_cache"

# Sync initial environment
RUN uv venv /opt/app-root --system-site-packages

RUN --mount=type=cache,target=$UV_CACHE_DIR \
    --mount=type=bind,source=uv.lock,target=$UV_PROJECT/uv.lock,relabel=shared \
    --mount=type=bind,source=pyproject.toml,target=$UV_PROJECT/pyproject.toml,relabel=shared \
    uv sync --active --no-install-project --extra $GUIDELLM_BUILD_EXTRAS

# Copy repository files
# Do this as late as possible to leverage layer caching
COPY / $UV_PROJECT

# Install guidellm
RUN --mount=type=cache,target=$UV_CACHE_DIR \
    uv sync --active --extra $GUIDELLM_BUILD_EXTRAS


# Prod image
#FROM $BASE_IMAGE

# Switch to root for installing packages
#USER root

# Install some helpful utilities and deps
RUN apt-get update && apt-get install -y --no-install-recommends \
        vim tar rsync ffmpeg \
        && apt clean

# Add guidellm bin to PATH
# Argument defaults can be set with GUIDELLM_<ARG>
ENV HOME="/home/guidellm" \
    GUIDELLM_OUTPUT_DIR="/results"

# Create the user home dir
WORKDIR $HOME

# Create a volume for results
VOLUME /results

# Switch back to unpriv user
# Root group for k8s
USER 1001:0

ENTRYPOINT [ "/opt/app-root/bin/guidellm" ]
CMD [ "benchmark", "run" ]
