name: 'Setup Python and uv'
description: 'Configures a Python version and uv'
inputs:
  python-version:
    type: string
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
    - name: Setup Python with UV
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ inputs.python-version }}
        enable-cache: "true"
