name: Feature Request
description: Suggest a new feature or enhancement for GuideLLM
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving GuideLLM! Please provide details about your feature request below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: I'm trying to do X, but currently GuideLLM doesn't support Y...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature or enhancement you'd like to see.
      placeholder: I would like GuideLLM to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried X, but it doesn't work because...

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: If applicable, provide examples of how this feature would be used.
      placeholder: |
        ```bash
        guidellm benchmark run --new-feature ...
        ```
      render: markdown

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, references, or examples that might help.
      placeholder: Links to similar features in other tools, mockups, etc...
