name: Development

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    strategy:
      matrix:
        python: ["3.10"]
    uses: ./.github/workflows/testing.yml
    with:
      python: ${{ matrix.python }}

  quality:
    strategy:
      matrix:
        python: ["3.10"]
    uses: ./.github/workflows/quality.yml
    with:
      python: ${{ matrix.python }}

  build-and-push-container:
    # Only build if the PR branch is local
    if: github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      packages: write
    uses: ./.github/workflows/build-multiarch-container.yml
    with:
      build-type: dev
      tag: pr-${{ github.event.number }}
