name: Development

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      matrix:
        python: ["3.10"]
    uses: ./.github/workflows/testing.yml
    with:
      python: ${{ matrix.python }}

  quality:
    strategy:
      matrix:
        python: ["3.10"]
    uses: ./.github/workflows/quality.yml
    with:
      python: ${{ matrix.python }}
