name: Quality Checks

on:
  workflow_call:
    inputs:
      python:
        required: true
        type: string

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run quality checks
        uses: ./.github/actions/run-tox
        with:
          python-version: ${{ inputs.python }}
          tox-env: lint-check,type-check,docs-build
      - name: Verify pre-commit checks
        run: |
          SKIP=ruff-format uv run --frozen --only-group env -- pre-commit run --all-files
