name: Quality Checks

on:
  workflow_call:
    inputs:
      python:
        required: true
        type: string

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run quality checks
        uses: ./.github/actions/run-tox
        with:
          python-version: ${{ inputs.python }}
          tox-env: quality

  type-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e6714ff5f5447ce83dd # v6.0.2
      - name: Run type checks
        uses: ./.github/actions/run-tox
        with:
          python-version: ${{ inputs.python }}
          tox-env: types

  precommit-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ inputs.python }}
      - name: Install dependencies
        run: pip install pre-commit
      - name: Run pre-commit checks
        run: SKIP=ruff-format pre-commit run --all-files
