name: Tests

on:
  workflow_call:
    inputs:
      python:
        required: true
        type: string
      args:
        required: false
        type: string

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run unit tests
        uses: ./.github/actions/run-tox
        with:
          python-version: ${{ inputs.python }}
          tox-env: test-unit
          tox-args: ${{ inputs.args }}

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run integration tests
        uses: ./.github/actions/run-tox
        with:
          python-version: ${{ inputs.python }}
          tox-env: test-integration
          tox-args: ${{ inputs.args }}

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run end-to-end tests
        uses: ./.github/actions/run-tox
        with:
          python-version: ${{ inputs.python }}
          tox-env: test-e2e
          # Default E2E uses in-tree MockServer (no llm-d Docker binary).
          # Rerun e2e tests due to flakyness in CI
          tox-args: --reruns=3 ${{ inputs.args }}
